### ISSUE TITLE
Stretch goal 1 - broadcast tweets vs. mentions

### ISSUE THREAD

**Issue by yuvalpinter** [ianbstewart/CSS_replication_project#11]
Dependencies: #9 and #8 finished.

**Comment by ianbstewart** [comment]
Results [here](../blob/master/scripts/experiment_2/experiment_2_addon.ipynb#Test-for-difference-in-reply-vs.-non-reply).

1. When considering only tweets that contain a referendum hashtag, reply tweets are **significantly** more likely to use Catalan ($d_{u}=0.179,p<0.01$).

2. When considering only tweets that contain at least one hashtag (referendum or non), reply tweets are not more likely to use Catalan.

3. When considering only tweets that contain no hashtags, reply tweets are not more likely to use Catalan.

4. When comparing @-replies without hashtags and non-replies with hashtags, reply tweets are **significantly** less likely to contain Catalan ($d_{u}=-0.0196,p<0.05$).

Not sure how to reconcile findings 1 and 4, since they seem to point to opposite effects!
