### ISSUE TITLE
Per-user statistics

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#30]
Compute and display (table? histogram?) the number of tweets per user to address concern about high-volume users.

**Comment by yuvalpinter** [comment]
Performed using `jq` and shell commands. Added to extraction segment of section 3. The control counts are saved (locally) under `data_processing.user_control_tweet_counts.txt`. It's odd that there are 67K+ users there (similar number if we key by twitter id) instead of the 10K that there should be. @ianbstewart follow up?...

**Comment by ianbstewart** [comment]
That is a weird discrepancy because I thought we only had 10K control users. Are you using `archive_Jan-01-17_Oct-31-17_ref_hashtags_filtered.json` to get the counts?

**Comment by ianbstewart** [comment]
Final control data is now under `data/tweets/extra_user_tweets/Jan-01-17_Oct-31-17_user_tweets_final.tsv`. The counts for total control tweets and languages have been updated in the paper. Thanks for the sanity checking on this one!
