### ISSUE TITLE
Intro

### ISSUE THREAD

**Issue by ianbstewart** [ianbstewart/CSS_replication_project#32]
Short but compelling introduction to political language variation and social media as a window into political processes.

**Comment by yuvalpinter** [comment]
I made a pass on sections 1-2 and think they're actually not bad. Maybe missing a single sentence in the first paragraph.
* Do you want to ask the opinions of our esteemed lab members? They can read just s.1-2.
* There's a todo regarding NLP methods for code-switching detection, are you still interested in todoing it? I'm not sure it's very pertinent since those works are probably about intra-tweet variation (no?)

**Comment by ianbstewart** [comment]
1. I would like to have feedback from the other CL folks. We can send out a draft tomorrow.
2. The code-switching stuff I was thinking of was definitely intra-sentential stuff (e.g. [this](http://www.aclweb.org/anthology/R15-1033)), so I don't think it's too relevant to our stuff. We can drop it.

**Comment by yuvalpinter** [comment]
We can add that distinction in the intro, since I think that's what people generally think of when they hear "code switching" (tbh the "code-mixing" thing threw me off first time I saw you use it, and the paper you're linking to seems to use the terms interchangeably for the same below-clause-level* phenomenon).
*I like that classification.
